package edeka

import (
	"context"
	"errors"
	"fmt"
)

// bearerLoginData is used as template data for the bearer-to-credentials exchange.
type bearerLoginData struct {
	Config
	AccessToken string
}

// ------------------------------------------------------------------------------
// Simple variants - use context.Background() and a default client with a 30-second timeout
// ------------------------------------------------------------------------------

// RegisterAnonymously registers a new device with the Edeka API using random device info.
// For control over context and HTTP client, use RegisterAnonymouslyCtx.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func RegisterAnonymously() (*Edeka, error) {
	return RegisterAnonymouslyCtx(context.Background(), nil)
}

// LoginWithCredentials validates an existing API token pair against the server.
// For control over context and HTTP client, use LoginWithCredentialsCtx.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func LoginWithCredentials(tokenID, tokenSecret string, device *DeviceConfig) (*Edeka, error) {
	return LoginWithCredentialsCtx(context.Background(), tokenID, tokenSecret, device, nil)
}

// LoginFromAuthFile loads credentials from edeka_auth.json in the CURRENT
// WORKING DIRECTORY and does a checkin. A process invoked from a different
// directory will read a different file. Use LoginFromCustomAuthFile with an
// absolute path for stable storage.
// For control over context and HTTP client, use LoginFromAuthFileCtx.
func LoginFromAuthFile() (*Edeka, error) {
	return LoginFromAuthFileCtx(context.Background(), nil)
}

// LoginFromCustomAuthFile loads credentials from the given path and does a checkin.
// For control over context and HTTP client, use LoginFromCustomAuthFileCtx.
func LoginFromCustomAuthFile(filepath string) (*Edeka, error) {
	return LoginFromCustomAuthFileCtx(context.Background(), filepath, nil)
}

// CredentialsFromBearer generates API credentials from a valid OAuth bearer token.
// Equivalent to RefreshCredentialsFromBearer(token, nil) - a random device config is
// generated. See RefreshCredentialsFromBearer for bearer-source and one-time-use details.
// For control over context and HTTP client, use CredentialsFromBearerCtx.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func CredentialsFromBearer(token string) (*Edeka, error) {
	return CredentialsFromBearerCtx(context.Background(), token, nil)
}

// RefreshCredentialsFromBearer generates API credentials using a known device config.
// Use this when the device config is already known (e.g., from an auth file) to avoid
// accumulating different device registrations on the account. If device is nil,
// a random device configuration is generated.
//
// The bearer can be copied from devtools after login at https://login.edeka/app.
// A bearer token can only be used once.
// For control over context and HTTP client, use RefreshCredentialsFromBearerCtx.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func RefreshCredentialsFromBearer(token string, device *DeviceConfig) (*Edeka, error) {
	return RefreshCredentialsFromBearerCtx(context.Background(), token, device, nil)
}

// ------------------------------------------------------------------------------
// Ctx variants - explicit context and HTTP client (nil client = default client with a 30-second timeout)
// ------------------------------------------------------------------------------

// RegisterAnonymouslyCtx registers a new device with the Edeka API using random device info.
// This results in credentials for an "anonymous" login, which gives access to some parts of the app.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func RegisterAnonymouslyCtx(ctx context.Context, client HTTPDoer) (*Edeka, error) {
	var config Config
	config.FillDefaults()
	config.DeviceConfig.Random()
	return registerAnonymouslyKnownConfig(ctx, config, client)
}

// LoginWithCredentialsCtx validates an existing API token pair against the server.
// The token pair is generated by CredentialsFromBearer during first-time setup.
// If device is nil, a random device configuration is generated. Pass an existing DeviceConfig
// to avoid accumulating different device registrations on the account.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func LoginWithCredentialsCtx(ctx context.Context, tokenID, tokenSecret string, device *DeviceConfig, client HTTPDoer) (*Edeka, error) {
	if tokenID == "" || tokenSecret == "" {
		return nil, fmt.Errorf("tokenID and tokenSecret must not be empty")
	}

	var config Config
	config.FillDefaults()
	if device != nil {
		config.DeviceConfig = *device
	} else {
		config.DeviceConfig.Random()
	}

	creds := Credentials{
		Username: tokenID,
		Password: tokenSecret,
	}

	ed := newEdeka(config, creds, client)
	if err := ed.validateCredentials(ctx, creds); err != nil {
		return nil, err
	}
	return ed, nil
}

// LoginFromAuthFileCtx loads credentials from the default path and does a checkin.
func LoginFromAuthFileCtx(ctx context.Context, client HTTPDoer) (*Edeka, error) {
	return LoginFromCustomAuthFileCtx(ctx, DefaultAuthFileName, client)
}

// LoginFromCustomAuthFileCtx loads credentials from the given path and does a checkin.
func LoginFromCustomAuthFileCtx(ctx context.Context, filepath string, client HTTPDoer) (*Edeka, error) {
	var a AuthFile
	err := a.LoadFromFilepath(filepath)
	if err != nil {
		return nil, err
	}

	var c Config
	c.FillDefaults()
	c.DeviceConfig = a.DeviceConfig

	ed := newEdeka(c, a.SoapCredentials, client)
	if err = ed.validateCredentials(ctx, a.SoapCredentials); err != nil {
		return nil, err
	}
	return ed, nil
}

// RefreshCredentialsFromBearerCtx generates API credentials using a known device config.
// If device is nil, a random device configuration is generated.
// A bearer token can only be used once.
//
// The flow starts with an anonymous device registration, which the server records
// before the bearer exchange runs. If any subsequent step (bearer exchange,
// checkRegistration, or checkin) fails, that anonymous registration remains on the
// server with no cleanup API - repeated failures accumulate phantom devices on the
// account.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func RefreshCredentialsFromBearerCtx(ctx context.Context, token string, device *DeviceConfig, client HTTPDoer) (*Edeka, error) {
	if token == "" {
		return nil, fmt.Errorf("bearer token must not be empty")
	}

	var config Config
	config.FillDefaults()
	if device != nil {
		config.DeviceConfig = *device
	} else {
		config.DeviceConfig.Random()
	}

	// bearerLogin requires Basic auth credentials, but a bearer-token holder has no
	// pre-existing SOAP credentials. Bootstrap via anonymous registration to obtain
	// temporary creds, wrap them in an *Edeka, and run the bearer exchange as a
	// method so endpoint overrides (e.g. in tests) actually apply. We skip the
	// post-registration checkin here because the temp creds are discarded
	// immediately after the bearer exchange - checkin would be wasted work.
	tempCreds, err := registerDevice(ctx, config, client)
	if err != nil {
		return nil, err
	}

	ed := newEdeka(config, *tempCreds, client)
	creds, err := ed.exchangeBearer(ctx, token)
	if err != nil {
		return nil, err
	}
	ed.creds = creds

	if err = ed.validateCredentials(ctx, creds); err != nil {
		return nil, err
	}
	return ed, nil
}

// exchangeBearer trades an OAuth bearer token for permanent SOAP credentials,
// using the current e.creds for Basic auth on the request. Called during the
// bearer-login flow once an *Edeka has been bootstrapped with temporary creds.
func (e *Edeka) exchangeBearer(ctx context.Context, token string) (Credentials, error) {
	data := bearerLoginData{
		Config:      e.config,
		AccessToken: token,
	}
	var envelope soapEnvelope[loginResponse]
	if err := e.callSOAP(ctx, e.endpoints.bearerLogin, data, &envelope); err != nil {
		return Credentials{}, fmt.Errorf("bearer login: %w", err)
	}
	response := envelope.Body.Response.Data
	if response.Username == "" {
		return Credentials{}, errors.New("sso response missing username")
	}
	if response.Password == "" {
		return Credentials{}, errors.New("sso response missing password")
	}
	return Credentials{
		Username: response.Username,
		Password: response.Password,
	}, nil
}

// CredentialsFromBearerCtx generates API credentials from a valid OAuth bearer token.
// Equivalent to RefreshCredentialsFromBearerCtx(ctx, token, nil, client) - a random
// device config is generated. See RefreshCredentialsFromBearerCtx for bearer-source,
// one-time-use, and device-registration details.
//
// The returned Edeka instance is not persisted. Call SaveAuth() or SaveAuthTo() to persist.
func CredentialsFromBearerCtx(ctx context.Context, token string, client HTTPDoer) (*Edeka, error) {
	return RefreshCredentialsFromBearerCtx(ctx, token, nil, client)
}

// Reauthenticate validates a new token pair against the server and updates the credentials
// on this Edeka instance in-place. For control over context, use ReauthenticateCtx.
func (e *Edeka) Reauthenticate(tokenID, tokenSecret string) error {
	return e.ReauthenticateCtx(context.Background(), tokenID, tokenSecret)
}

// ReauthenticateCtx validates a new token pair against the server and updates the credentials
// on this Edeka instance in-place, preserving all other configuration (Client, pagination settings, etc.).
func (e *Edeka) ReauthenticateCtx(ctx context.Context, tokenID, tokenSecret string) error {
	if tokenID == "" || tokenSecret == "" {
		return fmt.Errorf("tokenID and tokenSecret must not be empty")
	}

	creds := Credentials{
		Username: tokenID,
		Password: tokenSecret,
	}

	if err := e.validateCredentials(ctx, creds); err != nil {
		return err
	}

	e.creds = creds
	e.temporaryCreds = false
	return nil
}

// ------------------------------------------------------------------------------
// Registration Helpers
// ------------------------------------------------------------------------------

// registerAnonymouslyKnownConfig runs the anonymous registration flow for a known config.
// Uses defaultEndpoints because no *Edeka exists at call time.
func registerAnonymouslyKnownConfig(ctx context.Context, config Config, client HTTPDoer) (*Edeka, error) {
	creds, err := registerDevice(ctx, config, client)
	if err != nil {
		return nil, err
	}

	ed := newEdeka(config, *creds, client)
	ed.temporaryCreds = true

	// Checkin with the server to confirm the registration.
	// Not strictly required, but replicates the app's behavior.
	if err = ed.checkin(ctx, *creds); err != nil {
		return nil, err
	}
	return ed, nil
}

// registerDevice calls the anonymous-registration SOAP endpoint and returns the
// credentials it issues. Uses defaultEndpoints - no *Edeka exists yet.
func registerDevice(ctx context.Context, config Config, client HTTPDoer) (*Credentials, error) {
	var envelope soapEnvelope[registerAnonymousResponse]
	if err := doSOAPCall(ctx, client, config, nil, defaultEndpoints.registerAnonymously, config, &envelope); err != nil {
		return nil, fmt.Errorf("registering device: %w", err)
	}

	creds := &envelope.Body.Response.Data
	if creds.Username == "" {
		return nil, errors.New("registration response missing username")
	}
	if creds.Password == "" {
		return nil, errors.New("registration response missing password")
	}
	return creds, nil
}

// checkin notifies the server of a post-login event, using the supplied credentials.
// The creds argument is passed explicitly (rather than reading e.creds) because
// Reauthenticate calls this with prospective credentials before committing them.
func (e *Edeka) checkin(ctx context.Context, creds Credentials) error {
	if err := e.callSOAPWithCreds(ctx, e.endpoints.checkin, e.config, creds, nil); err != nil {
		return fmt.Errorf("checkin: %w", err)
	}
	return nil
}

// checkRegistration verifies that a credential pair is still valid on the server.
// See checkin for why creds is an explicit argument.
func (e *Edeka) checkRegistration(ctx context.Context, creds Credentials) error {
	if err := e.callSOAPWithCreds(ctx, e.endpoints.checkRegistration, creds, creds, nil); err != nil {
		return fmt.Errorf("checking registration: %w", err)
	}
	return nil
}

// validateCredentials runs checkRegistration followed by checkin with the
// supplied credentials. Every login entry point fires both to mirror the
// Android app's behaviour; this helper keeps that pair in one place.
func (e *Edeka) validateCredentials(ctx context.Context, creds Credentials) error {
	if err := e.checkRegistration(ctx, creds); err != nil {
		return err
	}
	return e.checkin(ctx, creds)
}
