package edeka

import (
	"fmt"
	"strings"
	"time"
)

// ReceiptParsed and ReceiptDetailsParsed have similar fields, but they are not the same, which is why they share receiptBase as a parent struct.
type receiptBase struct {
	// Unique ID of the receipt
	ID int

	// Contains information about the store the purchase was made in
	Shop ParsedShop

	// Contains information about the retailer the purchase was made with.
	// In this case it should always just be "Edeka".
	Retailer Retailer

	// The name of the phone that was scanned to generate this receipt.
	// Format: "{Manufacturer}{Model}"
	PhoneName string

	// The date and time the receipt was generated.
	DateAndTime time.Time

	// Whether a pdf is theoretically available. Not relevant for anything really.
	// The PDF is automatically sent to your email address but does not seem to be accessible otherwise or via the app.
	// Not sure why it's here
	IsPDFAvailable bool
}

// ReceiptParsed is a parsed version of the struct generated by the receipt-list endpoint.
// It can be generated by calling Parse() on a Receipt struct.
type ReceiptParsed struct {
	receiptBase

	// Includes information about how the receipt was paid, how much was paid and saved
	PaymentInformation PaymentInformation
}

// ReceiptDetailsParsed is a parsed version of the struct generated by the receipt-details endpoint.
// Only ReceiptDetails contain the items that were purchased. Apart from that, they are very similar to the base receipt struct.
// ReceiptDetailsParsed can be generated by calling Parse() on a ReceiptDetails struct.
type ReceiptDetailsParsed struct {
	receiptBase

	// The items that were purchased
	Items []ReceiptItem

	// Includes information about how the receipt was paid, how much was paid and saved
	PaymentInformation PaymentInformationDetails

	// Whether the receipt was canceled
	Canceled bool

	// If the receipt was canceled, this will contain the ID of the cancel transaction
	CancelTransactionID *int

	// Generic Receipt Footer
	Footer string
}

type ReceiptItem struct {
	Name     string
	Price    float64
	rawPrice string // original price string, used for merge comparison to avoid float equality

	// Whether the item has a Pfand (deposit)
	Pfand *float64

	// Whether the item was merged in the receipt.
	// For example, if you buy 2 cucumber for 1€ each, the struct will be:
	// Price: 2
	// Merged: true
	// Quantity: 2
	// UnitPrice: 1
	//
	// By default, this is the format done by edeka's system in two cases:
	// 1) IF the cashier does not scan each item, but instead scans one and enters the quantity.
	// 2) Items, which have a custom quantity by default, like cheese or meat you buy from the counter or fruits/vegetables you weigh yourself.
	// This is the reason the items cannot be "unmerged", even though this might complicate data output somewhat unnecessarily.
	// My implementation will merge other duplicate items too (→ when there are exact duplicates in terms of name and price
	// but the cashier scanned them one by one), so it is consistent.
	Merged         bool
	mergedManually bool

	// See description of Merged
	Quantity *float64

	// See description of Merged
	UnitPrice *float64
}

// ------------------------------------------------------------------------------
// Sub-Structs
// ------------------------------------------------------------------------------

// PaymentInformationDetails is used in ReceiptDetailsParsed
type PaymentInformationDetails struct {
	PaymentInformation

	// Whether product coupons were used
	CouponsUsed bool

	// Whether money coupons were used
	TenderCouponsUsed bool

	// Whether the receipt was paid with the app
	PaidWithValuephone bool
}

// PaymentInformation is used in ReceiptParsed
type PaymentInformation struct {
	// Total sum of the receipt
	Sum float64

	// Amount paid USING THE APP. Will be 0 if the receipt was paid by card or cash.
	// Also see Tenders.
	AmountPaidUsingApp float64

	// Amount saved by the customer
	Saved float64

	// Currency used to pay.
	// Contains the symbol of the currency used
	// as well as the position of the symbol in relation to the number.
	Currency Currency

	// Theoretically contains information about the tender(s) used to pay.
	// Currently, the only two types of tender the API returns are "VALUEPHONE" and "OTHER".
	// As such, there is no new information here or very little.
	Tenders []ReceiptTender
}

// ParsedShop is used in receiptBase
type ParsedShop struct {
	ShopNativeID    int
	ShopLogoImageID int
	Shop
}

// Retailer is used in receiptBase
type Retailer struct {
	CountryID int
	Name      string
}

// ------------------------------------------------------------------------------
// Basic To-String Functions
// ------------------------------------------------------------------------------

func (pi PaymentInformationDetails) String() string {
	s := pi.PaymentInformation.String()
	if pi.PaidWithValuephone {
		s += "\nPaid with app: yes"
	}
	return s
}

func (r receiptBase) String() string {
	return fmt.Sprintf(
		"--------------------------------------\n"+
			"Receipt %d\n"+
			"%s\n"+
			"Date: %s\n",
		r.ID,
		align(r.Shop.String()),
		r.DateAndTime.Format("02.01.2006 15:04"),
	)
}

func (ps ParsedShop) String() string {
	return ps.Shop.String()
}

func (pi PaymentInformation) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "Total: %.2f€", pi.Sum)
	if pi.AmountPaidUsingApp > 0 {
		fmt.Fprintf(&sb, "\nApp payment: %.2f€", pi.AmountPaidUsingApp)
	}
	if pi.Saved > 0 {
		fmt.Fprintf(&sb, "\nSaved: %.2f€", pi.Saved)
	}
	return sb.String()
}

func (r ReceiptParsed) String() string {
	return fmt.Sprintf(
		"%s"+
			"Payment\n"+
			"%s\n",
		r.receiptBase.String(),
		align(r.PaymentInformation.String()),
	)
}

func (r Retailer) String() string {
	return fmt.Sprintf(
		"Country ID: %d\n"+
			"Name: %s",
		r.CountryID,
		r.Name,
	)
}

func (ri ReceiptItem) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "%s: %.2f€", ri.Name, ri.Price)
	if ri.Merged && ri.Quantity != nil && ri.UnitPrice != nil {
		fmt.Fprintf(&sb, " (%.2f x %.2f€)", *ri.Quantity, *ri.UnitPrice)
	}
	if ri.Pfand != nil {
		fmt.Fprintf(&sb, " (+%.2f€ Pfand)", *ri.Pfand)
	}
	return sb.String()
}

func (rd ReceiptDetailsParsed) String() string {
	var itemsString string
	if len(rd.Items) == 0 {
		itemsString = "None"
	} else {
		var sb strings.Builder
		for _, item := range rd.Items {
			sb.WriteString(item.String())
			sb.WriteByte('\n')
		}
		itemsString = sb.String()
	}

	var sb2 strings.Builder
	fmt.Fprint(&sb2, rd.receiptBase.String())
	fmt.Fprintf(&sb2, "Payment\n%s\n", align(rd.PaymentInformation.String()))
	if rd.Canceled {
		fmt.Fprint(&sb2, "CANCELED")
		if rd.CancelTransactionID != nil {
			fmt.Fprintf(&sb2, " (transaction %d)", *rd.CancelTransactionID)
		}
		sb2.WriteByte('\n')
	}
	fmt.Fprintf(&sb2, "Items\n%s", align(itemsString))
	return sb2.String()
}

// ------------------------------------------------------------------------------
// Helper
// ------------------------------------------------------------------------------

func align(s string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		// Skip blank lines - otherwise a trailing "\n" turns into "  "
		// and mid-string blanks pick up cosmetic indent with no content.
		if l == "" {
			continue
		}
		lines[i] = "  " + l
	}
	return strings.Join(lines, "\n")
}
